In [ ]:
from day05 import crates

In [ ]:
ex = crates(3, [["Z", "N"], ["M", "C", "D"], ["P"]])

In [ ]:
ex.one_move(2,3)


In [ ]:
ex.stacks

In [ ]:
from io import StringIO
import csv

scsv = """text,with,Polish,non-Latin,letters
1,2,3,4,5,6
a,b,c,d,e,f
gęś,zółty,wąż,idzie,wąską,dróżką,
"""

f = StringIO(scsv)
reader = csv.reader(f, delimiter=',')
for row in reader:
    print(row)

In [ ]:
import csv


In [ ]:
data1 = (
    "id8141    360.242940   149.910199   11950.7\n"
    "id1594    444.953632   166.985655   11788.4\n"
    "id1849    364.136849   183.628767   11806.2\n"
    "id1230    413.836124   184.375703   11916.8\n"
    "id1948    502.953953   173.237159   12468.3"
)

In [ ]:
data1

In [ ]:
import pathlib

path = "data/ex_day05.txt"
puzzle_input = pathlib.Path(path).read_text()

init_crates, instructions = puzzle_input.split('\n\n')


In [ ]:
init_crates_list = init_crates.split("\n")
init_crates_list.reverse()
init_crates_list


In [ ]:
import re

int(re.findall(r"(\d) $", init_crates_list[0])[0])

In [ ]:
[1,4, 6, 15, 19][:-1]

In [ ]:
3*[] 

In [ ]:
positions = [4*i+1 for i in range(3)]

In [ ]:
test = init_crates_list[2]

In [ ]:
[test[pos] for pos in positions]

In [ ]:
x,y,z = 3, 4, 5

In [ ]:
x = [4,2]
x.append([12,9])

In [ ]:
x

In [ ]:
[4,2] + [9,12]

In [ ]:
x = [1,2,3,4,5]

In [ ]:
x[-3:]

In [ ]:
x[:-3]

In [11]:
import copy
from day05 import Stacks
stack1 = Stacks(2, [["A","B","C"], ["H","K"]])
stack2 = copy.deepcopy(stack1)
stack1.add(1, "K")
stack2.crates

[['A', 'B', 'C'], ['H', 'K']]

In [12]:
print(stack1.crates)
stack2.add(1, "L")
stack1.crates

[['A', 'B', 'C'], ['H', 'K', 'K']]


[['A', 'B', 'C'], ['H', 'K', 'K']]

In [13]:
stack2.crates

[['A', 'B', 'C'], ['H', 'K', 'L']]

In [16]:
x = [1,2,3,4,5]
x[:-5]

[]

In [1]:
for char in "hello":
    print(char)

h
e
l
l
o


In [10]:
len(set("hello"))

4

In [11]:
"hello"[2:4]

'll'

In [17]:
x = list(range(4, 10))
x.pop()

9

In [18]:
x.pop()

8

In [23]:
x = {"hey":4, "no":7}

In [24]:
x["d"] = 0

In [25]:
x

{'hey': 4, 'no': 7, 'd': 0}

In [28]:
x = "$ cd a"
print(x[:4])
print(len(x[5:]))


$ cd
1


In [30]:
"hello"[3]

'l'

In [31]:
size("hello")

NameError: name 'size' is not defined

In [33]:
x = ["hey", "there"]
x.append("no")


In [34]:
x.pop()

'no'

In [35]:
x.pop()

'there'

In [43]:
x = [0,1,2,3,4]

for (ind, k) in enumerate(x):
    x[ind+1] = 7
    print(x)
    print(k)

[0, 7, 2, 3, 4]
0
[0, 7, 7, 3, 4]
7
[0, 7, 7, 7, 4]
7
[0, 7, 7, 7, 7]
7


IndexError: list assignment index out of range

In [44]:
"hello+++"

'hello+++'

In [58]:
x = ["cool", "no", "sweet", "cool","no", "hey", "no"]

x.index("no",2)

4

In [55]:
k = "hello"
x = k[2:4]
x[1] = "+"
k

TypeError: 'str' object does not support item assignment

In [40]:
x = np.array([[False, True, True],[False,False,True]])

5

5

In [14]:
import numpy as np
x = np.array(x)
np.shape(x)

(1, 3)

In [17]:
x > np.array([[3,4,9],[2,4,6]] )

array([[ True, False, False],
       [ True,  True, False]])

In [18]:
np.repeat(-1, 10)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [28]:
np.empty((5, 5), bool)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [ ]:
np.

In [36]:
x.sum()

3

In [37]:
x = y = 5

In [75]:
x

array([[False,  True,  True],
       [ True, False,  True]])

In [78]:
x[:,2:0:-1]

array([[ True,  True],
       [ True, False]])

In [48]:
len(x[1,3:])

0

In [53]:
x[1,::-1]

array([ True, False, False])

In [54]:
x[1,:]

array([False, False,  True])

In [55]:
x[1,::-1][2]=True

In [95]:
np.nonzero(x[2:,1])[0].size

0

In [3]:
x = [0, 12, 3]
y = x[1]
x[1] = 7
y

12

In [8]:
x[1:2] = [12, 9]

In [9]:
x

[0, 12, 9, 9, 9]

In [10]:
x[len(x)]

IndexError: list index out of range